### ISSUE TITLE
Version 2.2 not opening with Mekanism v10.0.24.453

### ISSUE THREAD

**Issue by noeneto** [MorningSage/Mekanism_Addons#5]
The modpack has only Mekanism and Mekanism Addons and crash upon starting.

```
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:ResourceLoadProgressGuiMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.9.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- Head --
Thread: Render thread
Stacktrace:
	at morningsage.mekanismaddons.utils.EnumBuilder$EnumValueBuilder.getConstructorAccessor(EnumBuilder.java:99) ~[mekanismaddons:1.16.5-2.2] {re:classloading}
-- MOD mekanismaddons --
Details:
	Mod File: mekanismaddons-1.16.5-2.2.jar
	Failure message: Mekanism: Addons (mekanismaddons) has failed to load correctly
		java.lang.NoSuchMethodError: 'sun.reflect.ConstructorAccessor sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)'
	Mod Version: 1.16.5-2.2
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: 'sun.reflect.ConstructorAccessor sun.reflect.ReflectionFactory.newConstructorAccessor(java.lang.reflect.Constructor)'
Stacktrace:
	at morningsage.mekanismaddons.utils.EnumBuilder$EnumValueBuilder.getConstructorAccessor(EnumBuilder.java:99) ~[mekanismaddons:1.16.5-2.2] {re:classloading}
	at morningsage.mekanismaddons.utils.EnumBuilder$EnumValueBuilder.makeEnum(EnumBuilder.java:89) ~[mekanismaddons:1.16.5-2.2] {re:classloading}
	at morningsage.mekanismaddons.utils.EnumBuilder$EnumValueBuilder.init(EnumBuilder.java:55) ~[mekanismaddons:1.16.5-2.2] {re:classloading}
	at morningsage.mekanismaddons.items.upgrades.AddonUpgrades.<clinit>(AddonUpgrades.java:29) ~[mekanismaddons:1.16.5-2.2] {re:classloading}
	at morningsage.mekanismaddons.items.AddonItems.<clinit>(AddonItems.java:21) ~[mekanismaddons:1.16.5-2.2] {re:classloading}
	at morningsage.mekanismaddons.MekanismAddons.<init>(MekanismAddons.java:17) ~[mekanismaddons:1.16.5-2.2] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?] {}
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350) ~[?:?] {re:classloading,re:classloading}
	at java.lang.Class.newInstance(Class.java:645) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}
```

**Comment by MorningSage** [comment]
I believe this to be caused by the version of Java being used.  Thanks for posting, I'll look into this.

**Comment by noeneto** [comment]
Tested with java 8 and everything worked flawlessly. Would be possible to make the newer version work with java 15?

**Comment by omeranha** [comment]
@MorningSage hey man, can I talk with you on discord? add me: oMeranha#8071
I have an idea for you

**Comment by MorningSage** [comment]
> Tested with java 8 and everything worked flawlessly. Would be possible to make the newer version work with java 15?

Not sure, at the moment since I'm using black magic behind the scenes, lol.  Let me check into what's available in later versions.  For now, I'm leaving this open as a reminder.

Sorry for the inconvenience, noeneto.

**Comment by MorningSage** [comment]
> @MorningSage hey man, can I talk with you on discord? add me: oMeranha#8071 I have an idea for you

Hey, if you have an idea for something, open an issue here so that I can monitoring it.  Otherwise, I'll have ideas all over the place and it'll be hard to keep track of.  I'm always open to suggestions!

However, let's keep discussions here to this particular issue.

**Comment by NielsPilgaard** [comment]
> I believe this to be caused by the version of Java being used. Thanks for posting, I'll look into this.

Which java version seems to be the issue? I can't tell from the crash ^^'

**Comment by Dunkmania101** [comment]
Just in case it got missed, I submitted a PR that should fix this.
